### ISSUE TITLE
Deprecate on_foo as a default event handler

### ISSUE THREAD

**Issue by almarklein** [zoofIO/flexx#124]
The current event system allows naming methods `on_foo` which will be automatically converted to a handler for the "foo" event. The rationale is that its easier for simple handlers, and that it provides a clear mechanism for overloading event handlers in subclasses, similar to Qt's event system (not its signal/slot mechanism).

However, it also adds confusion. Especially if code uses both this construct and the `@event.connect` decorator. In terms of simplicity it only saves one line, so that's hardly worth it. As for the inheritance, this can probably be made to work with `@connect` as well (it might already do, need to check and add tests).

With all this in mind, I'm leaning towards removing this feature, unless there are strong objections, or use-cases for which it would still be useful.

**Comment by Korijn** [comment]
In the spirit of explicit > implicit, I think this would be an improvement. Especially for larger codebases, this would make code more consistent and therefore easier to understand.
