### ISSUE TITLE
flexx py2exe

### ISSUE THREAD

**Issue by githubyong** [zoofIO/flexx#131]
if flexx can used by py2exe ?  when i use this demo and tried to convert it to exe,it error:ImportError: No module named flexx_legacy

**Comment by almarklein** [comment]
I have never tried, but I do not see why not. On Legacy Python (2.7) you might need to add 'flexx_legacy' to your py2exe includes.

**Comment by githubyong** [comment]
I am sorry,what does "add 'flexx_legacy' to your py2exe includes" mean? it seems that all scripts and libs are auto assembled by py2exe.

**Comment by almarklein** [comment]
I presume that py2exe has a way to explicitly include certain libraries that py2exe fails to include by itself. At least cx_Freeze has that, and I would be surprised if py2exe did not. `flexx_legacy` is (needed on 2.7) is not found by py2exe because of the way it is imported.

**Comment by githubyong** [comment]
Yes,you are right,there is a way to manual includes by setup script which is simlar to cx_Freeze ,Thanks for give me the  right way.
But both are not easy to configure .
