### ISSUE TITLE
Tests with an actual browser

### ISSUE THREAD

**Issue by almarklein** [zoofIO/flexx#133]
* We might be able to test some stuff relatively easily as we have a high degree of control in the browser through ther websocket connection
* Selenium
* https://github.com/pytest-dev/pytest-splinter
* Saucelabs
* that other CI service who's name I forgot
*

**Comment by Korijn** [comment]
Any CI service with browser + webdriver installed should be compatible, e.g. Codeship :)

**Comment by Korijn** [comment]
After more reading I'm starting to like pytest-selenium as well... it apparently supports headless browsers as well.

http://pytest-selenium.readthedocs.io/en/latest/user_guide.html#quick-start

**Comment by almarklein** [comment]
Related to #12

**Comment by almarklein** [comment]
We do have `app/tests/test_live.py` that tests using XUL (firefox) on CI. The discussion continues in #210.
