### ISSUE TITLE
Allow passing initial properties to app.serve and app.launch

### ISSUE THREAD

**Issue by almarklein** [zoofIO/flexx#140]
```python
class MyObject(app.Model):

    @event.prop
    def foo(self, v=0):
        return float(v)

m = app.launch(MyObject, props=dict(foo=3))
```

Or maybe even `app.launch(MyObject, foo=3)`

cc @maxyme

**Comment by Korijn** [comment]
Just a minor suggestion, but if you're adjusting this anyway, might be nice to also allow URL override, so e.g. an app can listen on the root.

**Comment by almarklein** [comment]
@Korijn  do you mean like `app.start(hostname, port)`?  That's implemented on start since `app.serve` does not start the server, but only tells the server what apps to serve.

**Comment by Korijn** [comment]
Here's an example:

```python
app.serve(r"admin/*", MyAdminApp)  # served at http://hostname.ext/admin/
app.serve(MyUnimportantApp)  # served at http://hostname.ext/MyUnimportantApp/
app.serve(r"*", MyMainApp)  # served at http://hostname.ext/
```

And as far as arguments go, this is what I understood @maxyme suggested:

```python
class MyObject(app.Model):

    def init(self, foo=0):
        self.foo = foo

m = app.serve(MyObject, dict(foo=3))
```

But your approach based on properties also seems viable and is more in touch with Flexx!

I'm not sure how that would work in scenarios where you're, for example, only passing in information that is subsequently used to _initialize_ a property though:

```python
class MyObject(app.Model):

    def init(self, secret_sauce=None):
        self.foo = Foo(secret_sauce)

m = app.serve(MyObject, dict(secret_sauce="magic"))
```

**Comment by almarklein** [comment]
Aha, that makes sense. I was planning on allowing hosting apps on `http://hostname.ext` by e.g. naming an app `Index` or `Main`. But your suggestion makes much more sense.

I think I like the init being argumentless. The use-case that you described can in most cases be fixed by a smarter property setter (e.g. if not `isinstance(foo, Foo): ...`).

**Comment by Maxyme** [comment]
What @Korijn wrote is in line with what I was suggesting. I have a small suggestion, in line with the tornado request helper class: changing init for initialize, then there is no more confusion as to what happens in the init since it's in the parent class.
```
class MyObject(app.Model):

    def initialize(self, foo=0):
        self.foo = foo

m = app.serve(MyObject, dict(foo=3))
```

**Comment by almarklein** [comment]
Proposal:
* `app.serve(Cls, path, defaults)`
* `app.launch(Cls, webruntime, defaults, **runtime_kwargs)`
* `app.export(Cls, filename, defaults, ...)`

Where `defaults` is a dict that is going to be used as kwargs for instantiating the `Cls`, i.e. initial property values.

**Comment by Korijn** [comment]
Sounds good to me!

**Comment by almarklein** [comment]
For "routing", I think it's sufficient (and nice and simple) to only allow names that can be identifiers. If we decide to allow regexp like stuff, we can always add that at a later time.

What should be the name of the "main" app? 
* `app.serve(MyApp, '__index__')`
* `app.serve(MyApp, '__root__')`
* `app.serve(MyApp, '__main__')`
* `app.serve(MyApp, 'main')`
* `app.serve(MyApp, '')`

**Comment by Korijn** [comment]
In Django, this is how you route URLs to views:

```python
urlpatterns = [
    url(r'^$', main_views.homepage),
    url(r'^help/', include('apps.help.urls')),
    url(r'^credit/', include(extra_patterns)),
]
```

So the empty string (and only the empty string) matches the homepage in that example.

I think that should do well for us as well! It makes sense, since you want to serve the root app when the user enters _nothing_.
