### ISSUE TITLE
Provide means to send large (binary) data between Python and JS

### ISSUE THREAD

**Issue by almarklein** [zoofIO/flexx#143]
One intention of Flexx is to allow writing scientific-oriented apps, to make it easy to share ideas and results. Science needs data, e.g. nd arrays.

Possibilities:
- Send the data over the existing websocket. Downsides: we probably want to have a binary websocket then, and this implies that in exported apps, the commands are base64 encoded inside the html :/
- Send the data over an auxiliary websocket
- Send the data via Ajax. Seems to work great in Arbiter. This can be done in binary form and provides a similar mechanic to load data from the web instead of from Python. Can this made to work for exported apps (i.e. can the blob be loaded from a static file next to the HTML doc)?

**Comment by almarklein** [comment]
I think this should eventually be done via a second websocket connection. AJAX adds a delay (because you have to send a message to the client to make it ask the server for data), plus overhead for setting up an HTTP connection. With a binary websocket, the server can just push data to the client, which will enable much more sophisticated apps. 

We could make it such that exported apps use AJAX, and/or that its possible to point to remote resources which are gathered via AJAX.

**Comment by almarklein** [comment]
As for the API, maybe allow sending data to a model directly:

```py
class MyModel(app.Model):

    def some_function_or_handler(self):
        self.send_data(binary_blob, meta_info1)  # Gets send over Websocket
        self.send_data('http://some.com/resource.blob', meta_info2)  # Gets send via AJAX

    class JS:

        def receive_data(self, data, meta):
            """ This gets called when the data has been received.
            """
            if meta.foo:
                  ...
            else:
                  ...

```

**Comment by Korijn** [comment]
* How will you avoid blocking the server thread?
* You should probably use a [Service Worker](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API) to avoid blocking the UI thread on the client-side

**Comment by almarklein** [comment]
I'm pretty sure that, just as with AJAX, all the data is send by the browser without blocking the ui thread. There's a callback when a new message is received.

**Comment by Korijn** [comment]
Okay then. And the server thread?

**Comment by almarklein** [comment]
I am pretty sure it won't block; even `sock.send()` for a common socket does not.

**Comment by Korijn** [comment]
In that case: awesome!

**Comment by almarklein** [comment]
Starting to wonder if we should provide a means to send binary blobs over, or whether we support data in a more general sense, and handle the serialization.

**Comment by Korijn** [comment]
add_shared_data seems to work pretty nicely currently.
