### ISSUE TITLE
Reactive Programming?

### ISSUE THREAD

**Issue by almarklein** [zoofIO/flexx#15]
Wrote summary and ideas down here: https://github.com/zoofIO/flexx/wiki/Functional-Reactive-Programming

This issue should be more about API design and implementation.

### JS compat

Whatever API we come up with, we must be able to apply it to PyScript and have it work in JS too.

### Combining with "property" system

Input signals are quite similar to properties/traits. However, if we want to allow access to the signal object, we cannot do:

     > foo.title = 'new title'
     > foo.title
     new title   # -> should be <signal instance at 0x123>

Solutions:

* A: signal objects cannot be accessed directly, only indirectly by name. This means, however, that signals can only live on particular objects. Further, how do normal signals (non-input) look like then? Also, you want to be able to access the signal objects somehow, if only to debug. Also functional does not work naturally. So maybe this is just a variant of B.
* B: signal objects are somewhere else, e.g. at `foo.signals.title`. Ugh. Again, asymmetry with plain signal objects (not on a `HasSignals` instance).
* C: There are no properties `foo.title('new title')` sets the signal. I need to get used to this idea, but I think it can work. A benefit is that it allows for method chaining: `foo.title('new title').color('#f00')`.

Another benefit of *C* is that it becomes trivial to feed a signal output into an input. Maybe like:
```python
self.valid_input.react(self.okButton.enabled)
self.invalid_input.react(signals.not(self.okButton.enabled))
# or feed, connect, ...?
```

### Decorators

We specify a handful of decorators. 

```python

# For input, the function is used to clean/validate the input
@input
def title(v):
   return str(v)

# Normal signals have input signals and yield one signal
@signal('signal_a', 'signal_b')
def signal_absum(a, b):
   return a + b

# React signals get run on signal changes. They are (usually) end-points
@react('signal_absum')
def show_ab(v):
    print('the sum of a and b is ', v)
```

### Shorter syntax?

We could allow this:
```python
class Foo(HasSignals):
    title = Input(check_str)
    # or even
    title = Str()
    # and also
    title_lower = Signal(lower, ['title'])
```
... but then we need a metaclass to set the name at the class descriptor signals. If we stick to decorators, its more consistent and we don't need a meta class. Let's go with that for now. if ppl really want it, we can refactor to make use of a meta class.

**Comment by datnamer** [comment]
@almarklein Have you seen this?:http://multithreaded.stitchfix.com/blog/2015/07/16/pyxley/ 

Python-> React for creating flask dashboards. May have some good ideas or potential for combination or synergy with flexx.

**Comment by almarklein** [comment]
Hi @datnamer, no I haven't seen that yet. Thanks for the tip!

**Comment by almarklein** [comment]
RP is now implemented in `flexx.react`.
