### ISSUE TITLE
missing window decorations and close button

### ISSUE THREAD

**Issue by mash-graz** [zoofIO/flexx#161]
when a flex desktop app is lunched and a xul window appears, it does not show any resize or close buttons on the window itself. it's handled like a simple dialog by the window manager on linux.

**Comment by almarklein** [comment]
Thanks for reporting this! For the record (and in case it works on my Linux VM) what flavor of Linux are you experiencing this on?

**Comment by mash-graz** [comment]
i'm using the cinnamon desktop environment on debian linux.
i saw this problem with other multi platform applications as well.

when i analyze the x11 properties by 'xprop', i find a:
```
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DIALOG
```
this can be changed manually for a given window using: 
```
xprop -f _NET_WM_WINDOW_TYPE 32a \
     -set  '_NET_WM_WINDOW_TYPE' _NET_WM_WINDOW_TYPE_NORMAL
```
afterwards it works!

i think, this could be also changed by some additional keyword-arguments while launching the webruntime, but the values for the key 'windowfeatures' can not be modified unfortunately.

**Comment by almarklein** [comment]
Took a while, but this issue is reproduced, and fixed in https://github.com/zoofIO/flexx/pull/349/commits/fdaca6f3c83b46f50eaa5a592c65e37f2eb52180
(part of #349).
