### ISSUE TITLE
Notebook example - changing widget properties in handler

### ISSUE THREAD

**Issue by spencerogden** [zoofIO/flexx#166]
Sorry if this isn't something which should be raised as an issue, but I'm having trouble debugging futher being more of a python user and less familiar with js.

I am trying the example notebook "Apps in the notebook" with the Twente example. The example event handler doesn't seem to be working as expected. First we have:

`t = Twente(style='height:300px')`

Then the event handler, I inserted the print statements to try and see what was happening:

```
@t.connect('month.value')
def _change_line_color(*events):
    print("change")
    month = events[-1].new_value
    colors = ['red', 'green', 'blue', 'magenta', 'cyan', 'yellow'] * 2
    print( colors[int(month)])
    t.plot.line_color = colors[int(month)]
    print('finished')
```

This produces the print statements, but the plot does not change color: 

```
t.month.value =1
change
green
finished
```

This changes the plot color correctly:

```
t.plot.line_color = 'red'
```

Moving the slider, causing a change in `month.value` updates the plot data, but does not produces any print statements, or change the color of the plot. I'm not sure if the handler firing at all. 

I'm running this in Jupyter 4.1.0 and the latest Chrome. 

Am I missing something?

**Comment by almarklein** [comment]
Could it be that the cell that creates the app (and `t`) is run (again) after the handler is created? Or maybe another cell that defines a `t`?

**Comment by spencerogden** [comment]
Afraid, not, I am using the example notebook exactly as stored in GitHub 
with the exception of adding the print statements.

**Comment by almarklein** [comment]
Did you  restart and clear outputs before running the cells?

**Comment by almarklein** [comment]
Closing. The notebook support is being changed in #252 a lot. Please reopen if the problems persist after that PR is merged.
