### ISSUE TITLE
Embedding flexx inside PyQt/PySide

### ISSUE THREAD

**Issue by HenkHcks** [zoofIO/flexx#167]
Hi

Is it possible to embed a flexx application inside an existing PyQt application?
While still be able to interact between the flexx application and the PyQt application.
And this way facilitate a workflow where you are able to slowly migrate your application to flexx.

**Comment by almarklein** [comment]
Possibly. You could launch the Flexx-part of the application in a `QWebView`. There are two potential problems though:

### Problem 1 - integrating event loops

Flexx uses Tornado which needs a running event loop. I'm pretty sure though, that you can get away by periodically calling `ioloop.run_sync()` from a Qt timer.

### Problem 2 - running on Qt Webkit

Flexx is designed to work with modern versions of IE/Edge, Firefox, Chrome (and to some extend Safari). Some things might not work correctly on Qt's Webkit. You can test that by using `app.launch('pyqt')`. I just ran a few tests (discovered that the qt runtime was broken, fix in #168), and it seems none of the examples work with pyqt4.

Maybe with pyqt5, which might have a newer webkit version? It might be that we just need a bit of extra CSS to make at least part of the UI work.

**Comment by almarklein** [comment]
Note: the webruntime module does support pyqt, but none of the ui examples work in it.

**Comment by almarklein** [comment]
Just tried with PyQt5's webkit browser. Can't even get it to display the simplest of widgets. Let's forget about this ...
