### ISSUE TITLE
Variable-depth event connection strings

### ISSUE THREAD

**Issue by Korijn** [zoofIO/flexx#172]
_This issue is mostly meant to get some discussion going. It could very well turn out that I completely misunderstood some aspect of the current event system that already supports all this._

Imagine a `ComplicatedWidget` that contains a collection of widgets in an evented property `children`. Each of those widgets also contains a collection of widgets in an evented property `children`. Those widgets each have an attribute `slider` containing a `ui.Slider`.

Now, I want to subscribe to all the sliders that are in my `ComplicatedWidget`. Using dynamism, I understand from the docs that this is advertised to work as follows:

```python
class Example(ui.Widget):
    def init(self):
        self.cw = ComplicatedWidget()

    @event.connect('complicated_widget.children.*.children.*.slider.value')
    def on_slider_change(self, *events):
        pass
```

I don't like that I have to reach deep inside of `ComplicatedWidget` here. The point of that widget was to hide the complexity, so I can reuse it and change its internal composition without worrying about other code breaking. Obviously, if I decide to change the hierarchy, this code will break!

When I presented this to a colleague, they asked if I couldn't subscribe to the slider event by letting it bubble up instead, similar to how JS events traverse the DOM. Here's an example of what I would imagine this to look like:

```python
class Example(ui.Widget):
    def init(self):
        self.cw = ComplicatedWidget()

    @event.connect('slider.value')  # this bubbles up the hierarchy and is caught here
    def on_slider_change(self, *events):
        pass
```

You can make it just as flexible as JS event bubbling by exposing `stopPropagation()` and `preventDefault()` on the event object:

```python
    @event.connect('slider.value')
    def on_slider_change_2(self, *events):
        for ev in events:
            ev.stopPropagation()  # don't let the event bubble up any further
            ev.preventDefault()  # prevent the default handler of this event from running (which would be the update of the slider itself?)
```

A second weakness is that by subscribing to the event using the attribute name, I also risk code breakage if the evented `slider` property is renamed. Maybe subscribing to the event by source would be even more robust? E.g.:

```python
class Example(ui.Widget):
    def init(self):
        self.cw = ComplicatedWidget()

    @event.connect('value', source=ui.Slider)
    def on_slider_change(self, *events):
        pass
```

(this bears some similarity to Django receivers: https://docs.djangoproject.com/es/1.10/topics/signals/#connecting-to-signals-sent-by-specific-senders)

**Comment by almarklein** [comment]
I think that as it is now, the best approach would be to expose the event on the ComplicatedWidget Directly:

```python
class ComplicatedWidget:
    ...
    @event.emitter
     def slider_value(self, ev):
        """ Proxy event for the sliders inside the complicated widget. """
         return ev  # Just duplicate the incoming event
    
   @event.connect('children.*.children.*.slider.value')  # long, name, but ok, since we're inside the Complicated Widget now
    def _proxy_slider_events(self, *events):
        for ev in events:
            self.slider_value(ev)
```

**Comment by almarklein** [comment]
This should in principle solve your problem, though you'd have to write/maintain some extra code.

I am not against a more sophisticated approach offered by the event system, though we'd have to design it carefully, as it makes the system more complex. Maybe we need to collect a few different use-cases first.

**Comment by almarklein** [comment]
An approach where events are bubbled and then allowing users to prevent that will not work, for the same reasons mentioned in #174. So the solution would have to be in a smarter "connection string". Maybe '*.slider.value' or something?

**Comment by ivoflipse** [comment]
Connecting to `children` is basically a shorthand to listen to all widgets embedded in the current widget? Then `*.children` means also connect to the children of all widgets of my children?

**Comment by Korijn** [comment]
Some versions of glob use `**` as a variable-depth connection, so mirroring that, `some.very.**.deep.value` would then match all of the below:

* `some.very.deep.value`
* `some.very.very.deep.value`
* `some.very.very.very.deep.value`

You can also take inspiration from regexes, where `*` is greedy by default, and can be made non-greedy by appending a question mark, as in `*?`.
