### ISSUE TITLE
Stopping JS event propagation

### ISSUE THREAD

**Issue by almarklein** [zoofIO/flexx#174]
We need a way to allow the user to influence whether certain events (mouse, scrolling, keyboard) are allowed to bubble up, or whether their default action should be prevented.

This is pretty much impossible to do by letting handlers call a method on the event object because:
* events are supposed to be plain objects that can be send to Python, so methods would have to be special attributes.
* more importantly, events are scheduled at the event handlers and called in a next event loop iteration, which means that you'd be too late.

I think we need something like a property on `Widget` that you can set per-widget to prevent propagation of certain events. Maybe a `w.prevent_event_default = True`, though maybe something that can be more specific (e.g. allow context menu, but not scrolling).

Kind of events we may want to "catch":
* Context menu
* Scrolling
* Key events (think F5 and other browser shortcuts etc.)
* Middle mouse button, to prevent anchor cursor
* Mouse down/up/move events ?  I don't think this is necessary, ~~because there are no "default actions", right?~~ There are. Context menu on Firefox, and checking a radio button or checkbox goes via "default action".

Context menu is already prevented, otherwise we cannot capture right mouse button clicks. The disadvantage is that you cannot open the browser context menu anymore, e.g. to show the source. We can be smarter about that.

**Comment by almarklein** [comment]
cc @korijn

**Comment by ivoflipse** [comment]
Could we allow right mouse somewhere outside the canvas? You shouldn't have to prevent the default behavior for all widgets right? So the top level widget would still allow the context menu, if there are pixels visible for you to click on

**Comment by Korijn** [comment]
There's also the "drag anchor" that appears when you click the middle mouse button in most browsers.

**Comment by almarklein** [comment]
@ivoflipse yes, I'd like that. We can probably make it prevent default for context menu only if a handler is registered for the mouse down event (since we don't have separate events for each button).

**Comment by almarklein** [comment]
This seems like a thing that you want to set per class, not per instance. So it would probably be better to do something like:

```py
class MyWidget(ui.Widget):
    PREVENT_DEFAULT_EVENTS = 'context', 'key'
```

I wonder if we need to make a distinction between preventing bubbling and preventing a default action. If we prevent bubbling up, is the default action also prevented?

**Comment by Korijn** [comment]
No, the two actions are independent, see .e.g  http://stackoverflow.com/a/5963688/552379

How about adding an option? E.g.  `@event.connect('mouse_click', prevent_default=True)` seems like something that allows for some flexibility.

**Comment by Korijn** [comment]
Actually, that might also enable a function that runs on the event object:

```python
@event.connect('mouse_click', prevent_default=lambda ev: ev.button == 2)
```

**Comment by almarklein** [comment]
I'm not sure if a handler is the most sensible place to control the propagation/default behavior at the place where the event is defined, because there can be multiple handlers, and they could impose conflicting rules.

**Comment by Korijn** [comment]
RIght, I didn't realize that multiple handlers can be attached to the same (mouse) event. Although, I think that the fact that you can impose conflicting rules, shouldn't be a problem. You can use labels to make sure the right event gets fired first, or refactor your event handlers so the problem goes away, no?

I'm not completely opposed to the class attributes as settings, but it's not the first thing that I imagine would come to mind when a dev is trying to configure their event handler.

**Comment by almarklein** [comment]
> but it's not the first thing that I imagine would come to mind when a dev is trying to configure their event handler.

I agree with you on that. Though there are other cases where a class attribute is used (e.g. to influence whether events should be synced with Python). So it might be a common path to "configure" Model/Widget classes. Needs better docs then though.

**Comment by almarklein** [comment]
From another discussion, now that emitters allow `super()`, this is possible:
```py
@event.emitter
def mouse_down(self, e):
  e.preventDefault()
  return super.mouse_down(e)
```

This might be flexible enough? Though its much longer than `PREVENT_DEFAULT_EVENTS = 'mouse_down', 'mouse_up'` especially if there's multiple emitters to which this should be done.

**Comment by Korijn** [comment]
This seems like a very pleasant way to handle it, especially since you can make your calls to `preventDefault` conditional at runtime!

The remapping of mouse buttons in `super.mouse-down` might lead to some confusion though. Let's say you only call `preventDefault` for mouse button 2... :)
