### ISSUE TITLE
More helpful error message when accidentally overwriting reserved properties like self.container

### ISSUE THREAD

**Issue by Korijn** [zoofIO/flexx#176]
```python
class Foo(ui.Widget):
    def init(self):
        with ui.VBox() as self.container:
            # remainder of widget construction here
```

This seems like a natural name for the "container" of the subwidgets, but surprise: this will break your application, because `self.container` is already used internally. This could use a more helpful error message than `Host is not attached.`!

**Comment by almarklein** [comment]
In this particular case, container should also be constrained to be a string, I guess.
