### ISSUE TITLE
Widget for representing HTML elements (Div, etc.)

### ISSUE THREAD

**Issue by Korijn** [zoofIO/flexx#177]
Having something like the [Bootstrap grid](http://getbootstrap.com/css/#grid) makes development of responsive layouts super-easy. I suppose this could be integrated into Flexx relatively easy by providing a property on Widgets with which you can set [flex-wrap](https://css-tricks.com/almanac/properties/f/flex-wrap/), or by providing properties with which you can set the breakpoint from which they hold (like Bootstrap's `col-md-2` etc.).

This will probably require some discussion! We could alternatively look into enabling the use of systems like Bootstrap, although I don't see a short path to get there...

**Comment by Korijn** [comment]
Gave this some more thought and wrote some things down. It's quite a lot, apologies in advance for that.

In order to realize a semantically correct HTML/CSS based layout without jumping through hurdles, we'd need to borrow a bit more from react.js, in the sense that we need to be able to provide class names, and that widgets should map directly to HTML elements. E.g. to implement a comment box widget using Bootstrap, we'd need something like the following, where a new `html` module is introduced that has widgets which map 1:1 to HTML elements. This `html` module can live independently from the `ui` module, allowing two methods of constructing an interface to users.

```python
class Comment(ui.Widget):
    @event.prop
    def author(self, val):
        return val

    @event.prop
    def date(self, val):
        return val

    @event.prop
    def content(self, val):
        return val

    def init(self):
        with html.Div(className="row comment-meta"):
            self.author_div = html.Div(className="col-md-6 comment-author")
            self.date_div = html.Div(className="col-md-6 comment-date")
        with html.Div(className="row comment-content-container"):
            self.content_div = html.Div(className="col-xs-12 comment-content")

    @event.connect('author')
    def on_author(self, *events):
        self.author_div.text = events[-1].new_value

    @event.connect('date')
    def on_date(self, *events):
        self.date_div.text = events[-1].new_value

    @event.connect('content')
    def on_content(self, *events):
        self.content_div.text = events[-1].new_value
```

We can place it in a page like this and our Bootstrap layout should work:

```python
class Page(ui.Widget):
    @event.prop
    def comments(self, val=None):
        if val is None:
            val = []
        return val

    def init(self):
        with html.Div(className="container") as self.comment_container:
            self.comment_widgets = []
            for comment in self.comments:
                self.comment_widgets.append(widgets.Comment(author=comment['author'], date=comment['date'], content=comment['content']))

    @event.connect('comments')
    def on_comments(self, *events):
        for w in self.comment_widgets:
            w.parent = None
        self.comment_widgets = []
        for comment in self.comments:
            self.comment_widgets.append(widgets.Comment(author=comment['author'], date=comment['date'], content=comment['content']))
```

Borrowing `render()` from react.js would allow state management to simplify. Flexx can tell when a property changes, and thus know when to re-render the widget:

```python
class Comment(ui.Widget):
    @event.prop
    def author(self, val):
        return val

    @event.prop
    def date(self, val):
        return val

    @event.prop
    def content(self, val):
        return val

    def render(self):
        with html.Div(className="row comment-meta"):
            html.Div(className="col-md-6 comment-author", text=self.author)
            html.Div(className="col-md-6 comment-date", text=self.date)
        with html.Div(className="row comment-content-container"):
            html.Div(className="col-xs-12 comment-content", text=self.content)
```

react.js has reduced boilerplate by giving widgets an automatically evented `props` property (and `state` too, which is like `props` but private), and providing a method where you can provide the initial state:

```python
class Comment(ui.Widget):
    def init(self):
        return dict(author=None, date=None, content=None)

    def render(self):
        with html.Div(className="row comment-meta"):
            html.Div(className="col-md-6 comment-author", text=self.props.author)
            html.Div(className="col-md-6 comment-date", text=self.props.date)
        with html.Div(className="row comment-content-container"):
            html.Div(className="col-xs-12 comment-content", text=self.props.content)

class Page(ui.Widget):
    def init(self):
        return dict(comments=[])

    def render(self):
        with html.Div(className="container"):
            for comment in self.props.comments:
                widgets.Comment(author=comment['author'], date=comment['date'], content=comment['content'])
```

The [react.js tutorial](https://facebook.github.io/react/docs/tutorial.html) provided some key insights that lead to this post.

**Comment by Korijn** [comment]
The default style prevents vertical scrollbars on the window. I had to make some changes to the default Flexx styling. This particular example has `min-height` equal to the viewport-height (using `vh` units), so that the footer element will stick to the bottom, even if there isn't enough content to push it all the way down. If there's more content than can fit the window, you'll get a vertical scrollbar, as desired for a responsive layout.

```python
from flexx import app, ui


class ResponsiveApp(ui.Widget):
    CSS = """
    body {
      /* make sure the page has _at least viewport height_ so that the footer sticks to the bottom, even if there
         is not enough content
      */
      display: flex;
      min-height: 100vh;
      flex-direction: column;
      /* reset flexx default style */
      height: auto;
    }

    .flx-main-widget {
      /* this magic widget needs to stretch to fit <body>, to allow the footer to stick to the bottom of the viewport */
      flex: 1;
      /* reset flexx default style */
      width: auto;
      height: auto;
    }
    """

    def init(self):
        with ui.VBox():
            ui.Label(text="Header.")
            with ui.Widget(flex=1):
                self._content = ui.Label(text="Some content.", wrap=True)
            ui.Label(text="Sticky footer.")
```

**Comment by almarklein** [comment]
Notes after discussion:
* Scrolling can be implemented on a widget (using `overflow-y:scroll`), which will make the case above much easier (no fiddling with the CSS of `body`).
* A `ui.Div` element would help web developers a lot to "do their thing" inside a Flexx app.
* Additionally, a `ui.html` object that can be used to do `ui.html.Ul(...)` to generate `Div` elements of specific types would make things even easier (and scales better than implemening a separate Widget for each possible html element).
* As mentioned elsewhere, the docs on how to load additional assets should be improves.
* A section in the docs on how to use Flexx as a web dev would be nice.
