### ISSUE TITLE
Can not call  jQuery function

### ISSUE THREAD

**Issue by FunnyAlex** [zoofIO/flexx#191]
I can found the sample: with_jquery.py, but the sample don't include how to call a jQuery function, when I call the function with the node, I just get a error like this:`TypeError: this.modal_sample.node.modal is not a function`.  How to call a jQuery function with the node.

**Comment by almarklein** [comment]
This line shows where the jQuery gets called: https://github.com/zoofIO/flexx/blob/master/flexx/ui/examples/with_jquery.py#L17-L19  It's some raw JS in a docstring (in PyScript, methods that have a docstring and nothing else will use that docstring as raw JS).

On current master (and possibly the latest release) the jquery example is broken though.

**Comment by almarklein** [comment]
Closed per #196
