### ISSUE TITLE
Document init() and event handling cycle

### ISSUE THREAD

**Issue by Korijn** [zoofIO/flexx#192]
It's hard to figure out in which order event.properties are set, the init() function is called, events are emitted, and handlers are executed. Some examples and a thorough explanation would be very welcome!

**Comment by almarklein** [comment]
Good one. This part took so much effort to get right, and I think it works pretty neat now, but it's under (not?) documented ...

**Comment by Korijn** [comment]
Some examples of good UI lifecycle documentation:

* https://msdn.microsoft.com/en-us/library/ms178472.aspx
* https://www.appveyor.com/docs/build-configuration/#build-pipeline (not a UI, but still clearly laid out)
* http://www.asp.net/mvc/overview/getting-started/lifecycle-of-an-aspnet-mvc-5-application

This stuff is mostly important to the custom widget developer. Perhaps introducing a section for this topic would be nice?
