### ISSUE TITLE
Integration with cyclepy

### ISSUE THREAD

**Issue by TylorS** [zoofIO/flexx#22]
I made a quick python port of [cycle.js](https://github.com/cyclejs/cycle-core) here at [cyclepy](https://github.com/tylors/cyclepy). I did this mostly just as an exercise. When I saw you project I wondered if it would be possible to use it to somehow to update the ui.

Do you think this would be possible?

**Comment by almarklein** [comment]
I am not familiar with these projects, so its hard for me to say. What would you need from Flexx to do what you want?

**Comment by TylorS** [comment]
To put is as simple as possible, Cycle uses observables (rx) with cyclical
dependencies (drivers). So a driver listens to an observable and emits an
observable. This is extremely useful with a UI.

So an integration would be in the form of a driver, which would take an
observable that emits a tree/object that describes what the current view
should look like. I guess that's what I would need flexx to do. This driver
would also send back a way to listen to events (clicks, text input, etc...)
In which the developer would be able to tell flexx how to update the ui.

Let me know if you need me to try and clarify anything. Thanks for your
reply!

**Comment by almarklein** [comment]
As I understand it, you're looking for a way to connect Flexx's events/signals to Cycle, as well as (part of) the rendering. I would recommend having a look at the implementation of some of the widgets, and see how you can create a custom widget that suits your needs.

I suspect you'd need to load some JS to get things working. Loading custom JS is something on the todo-list, but you can probably hack your way out of this by including a `<scrip>` DOM element from JS.

**Comment by TylorS** [comment]
Okay, I'll definitely look into this at some point. Thanks for your suggestions!

**Comment by almarklein** [comment]
You can now load additional JS and CSS, which should make it easier to do what you want. See the [docs](http://flexx.readthedocs.org/en/latest/app/api.html#session-and-assets) and [this example](https://github.com/zoofIO/flexx/blob/master/examples/ui/with_jquery.py)
