### ISSUE TITLE
URL scheme

### ISSUE THREAD

**Issue by almarklein** [zoofIO/flexx#231]
In Flexx, apps are always hosted at `http://a.b/app_name`. Issue #189 proposes a routing mechanism by providing a url path relative to the app, e.g. `http://a.b/app_name/extra/info`.

At this point, assets are loaded relative to the current page. This is a bit odd, since most assets are common to all apps and sessions. Moreover, this will break down when we implement #189.

In #225 I am working on a major refactoring of the asset management. Let's pick sensible url's now.

Proposal:
- "app_names"  with an underscore are reserved. In other words, apps are always hosted at a path that does not start with an underscore. We now have `__index__` , `__main__` and `__cmd__` as special names, these will become `_index`, `_main` and `_cmd`.
- We get `_assets/` for all CSS and JS assets
- We get `_assets-debug/` or similar to show assets including line numbers. Links in traceback should link to these url's.
- We get `_data/` for images, scientific data, etc.
- Assets and data can be global or specific to the session. A session can be "selected" by doing `/_assets/foo.js?session_id=...`.  Or maybe `_assets/session_.../foo.js` ?
- Exported apps can either be a singleton HTML doc or an index.html with assets and data in dirs `_assets` and `_data`. Maybe have an option to put all assets and data in the same dir as the index? We'll see.

**Comment by Korijn** [comment]
* `_assets-debug/` seems like a workaround for a solved problem; most packers/minifiers support generating source maps on the fly: https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Use_a_source_map
* will you continue to support hosting an app at the root?
* Session-specific assets is pretty wild; It (used to be) uncommon practice on the web and the purpose in Flexx is not entirely clear to me. Will it be used to serve only those specific parts of the app that the user is seeing?

Much appreciated that you are taking #189 into account. :)

**Comment by almarklein** [comment]
Having source maps would be great, but then I'd need to make Flexx generate them. The `_asset-debug` thing is an easy step in the right direction (most of the code was already there).

> will you continue to support hosting an app at the root?

Of course. Right now an app must be served at "__main__", this will then be done via "_main".

Session-specific assets include the class definitions of classes that are not in a predefined module. Others can be more like "app-specific", e.g. an app that uses Bokeh or JQuery. Further, (scientific) data that is to be send from server to client can be session-specific. E.g. on a server that hosts an app that shows volumetric data to users, you don't want to store all that data globally, but have it destroyed when the session gets deleted :)

**Comment by almarklein** [comment]
Per #271 this has become:

* '/flexx/' is a reserved url prefix (there can be no app called "flexx"), and everything that is not an app serves from here.
* Websocket: `/flexx/ws`
* Assets: `/flexx/assets/shared/` and `/flexx/assets/<session id>/`
* Data: `/flexx/data/shared/` and `/flexx/data/<session id>/`
* Info: `/flexx/info`

Further, assets and data can also be accessed via a relative path (relative to the app), e.g. `_data/foo.png` or `_assets/bar.js`. This allows writing code that works for exported apps and served apps.
