### ISSUE TITLE
How to write a JS module

### ISSUE THREAD

**Issue by Korijn** [zoofIO/flexx#244]
In Python and JS to write some reusable functions you would put them in a separate file and just import that. How does this work in Flexx? How do I make a simple JS module? :)

**Comment by almarklein** [comment]
Coming up! It will soon be something like:
```py

app.assets.add_shared_asset(
    name='mystuff.js',
    sources=[pyscript, compatible, elements, 'and', 'raw', 'JS'],
    deps=[],
    exports=[]  # names of PyScript-stuff automatically get exported.
)
```

And you can then make this module a depency of other modules. Alternatively, you can add these sources directly to the module where they're needed.

**Comment by Korijn** [comment]
So how would you go about making use of such a JS module in a Widget's JS subclass?

**Comment by almarklein** [comment]
The Widget that needs functionality from `mystuff.js` would add it as a dependency:

```
classes = app.assets.get_module_classes('my.module')  # get list of Model classes defined in my.module

app.assets.add_shared_asset(
    name='my-module.js',
    sources=classes + [...],
    deps=['mystuff.js as mystuff'],
    exports=[]
)
```

And inside your `Widget` you can use `mystuff.foo`. Or, you could do `... sources=classes + ['var foo = mystuff.foo;']` to make it easier accessible.

I am playing with the idea whether the import syntax can be useful here. E.g. `from mystuff import foo`. But that would be more like syntactic sugar.

**Comment by almarklein** [comment]
Ideas on how to improve the writing up of the binding are welcome.

**Comment by almarklein** [comment]
Ha! Now (#271) there is no more need to write a JS module. Though you can still make a module be transpiled as a whole by defining `__pyscript__ = True`. Than just import that module where you need it and use it!
