### ISSUE TITLE
Unicode glyphs in tree widget not showing

### ISSUE THREAD

**Issue by JohnLunzer** [zoofIO/flexx#247]
On the readthedocs page for some widgets my computer is not able to render certain characters.

For example for the TreeWidget the expansion "icon" is trying to render a character but all I see is boxes containing "23F7" for expanded and "23F5" for contracted. This occurs with IE/Chrome/Firefox. Is this expected behavior? 

I'm on a pretty standard windows7 installation. Maybe there are some more common default choices.

**Comment by Korijn** [comment]
Maybe charset meta tag / http header is not properly emitted by flexx?

**Comment by almarklein** [comment]
Mmm, My guess is that the font being used does not contain these Unicode glyphs. I assumed that these glyphs would be available in all the common fonts. Guess I was wrong. 

Perhaps we should set the fonts in these places to one that we know contains the glyphs (and are present on a lot of systems). Or maybe even ship a font? (e.g. FontAwesome).

**Comment by almarklein** [comment]
Combobox should also be affected.

**Comment by JohnLunzer** [comment]
Yes, Combo box is affected. I'm supportive of shipping a font, it's the only way to absolutely ensure those glyphs are present, additionally should help create a common viewing experience.

**Comment by Korijn** [comment]
Would like to mention that best practises on the web recommend sticking to safe characters and fonts, for legibility with screen readers or oddball devices. Anyhow,  the added font will work, although it's a pretty big overhead just for a glyph or two.

**Comment by Korijn** [comment]
You'll find that supporting them crossbrowser is typically quite complicated.

**Comment by JohnLunzer** [comment]
It needn't be just a glyph or two. FontAwesome has awesome stuff in it. It was originally designed for bootstrap so it seems like it shouldn't be too hard to support cross browser, or at least it shouldn't be hard to find out.

**Comment by JohnLunzer** [comment]
Looking at the list of characters that font awesome has, http://fontawesome.io/cheatsheet/, it is very easy to see the _wide_ range of applications it would have within Flexx. In fact, it seems like a perfect fit for a lot of cases. 

Any of the fa-plus and fa-minus icons would be ideal for the the tree widget.

**Comment by Korijn** [comment]
It's not that I don't see the value; I just think the custom font doesn't need to be a dependency by default. As in, my application doesn't need it, so why would I have to incur the page load time hit?

**Comment by almarklein** [comment]
I agree that fontawesome is great, and see value in making it real easy to use from Flexx. But I agree that it should probably not be a default dependency. Also for the reason that it would remove the capability to export an app to a single HTML page.

**Comment by JohnLunzer** [comment]
Agreed.

Maybe this CSS based solution would work for the TreeWidget expand and contract "icons"?
http://jsfiddle.net/jlunzer/p9ghktfb/

It's not perfect but I think the aesthetic works. float and margins are only there for presentation.

**Comment by almarklein** [comment]
That's a nice and robust solution for at least the collapse/expand button, thanks! I will look into the fonts a bit too, but need to fire up my win7 VM for that. BTW, does the checkbox look ok, and is this issue present in all browsers?

**Comment by JohnLunzer** [comment]
I tried in most recent Stable Firefox/Chrome and IE11, all displayed the same missing character glyph.

**Comment by JohnLunzer** [comment]
And yes, the checkbox class looks okay.

**Comment by JohnLunzer** [comment]
Just checked this out, the more common glyphs show up on my machine and are a suitable replacement. 

I think there is still room for more pleasing aesthetics on the tree widget, but I'm sure you've got bigger fish to fry and what we've got now will is good enough. If I get some time I might try to implement the CSS solution in the tree widget.

**Comment by almarklein** [comment]
Awesome! Thanks for reporting this, BTW.

I'm sure there are things we can do to make it look better, but such tweaks are not my strong suit :)
