### ISSUE TITLE
would it be possible to have it in wheel format on pypi ?

### ISSUE THREAD

**Issue by stonebig** [zoofIO/flexx#26]
````
python setup.py sdist bdist_wheel  --universal
twine upload dist/*

````

**Comment by almarklein** [comment]
Being pure Python, and without extensions or binaries, what would be the benefit?

**Comment by stonebig** [comment]
clean installation process with no execution of just downloaded code.
getting all the benefits of latest pip versions (like requirements.txt files).

getting rid of legacy python packaging methods, so the pypa community can move forward (and go clother to conda-style in next step)

when all packages are wheels, especially on windows, life is really easier.

**Comment by almarklein** [comment]
Done. I uploaded a wheel for v0.1 to pypi, and made a note in setup.py so that I will (probably) remember it for the next release.

**Comment by stonebig** [comment]
thanks !

**Comment by stonebig** [comment]
I don't catch exactly what I have in front of me when launching the twente_temperature example under winpython Qt5:
- it's Qt5 ?
- it's my browser ? 
- it's the browser motor of Qt5 ?

**Comment by almarklein** [comment]
You can check by printing `m.proxy._runtime` (I suppose `runtime` should be made a public prop). It's most probably the Xul runtime, which is a firefox browser trying to look like a desktop app.

If you change the last lines to:
```python
if __name__ == '__main__':
    m = app.launch(Twente, 'pyqt', title='Temperature 1951 - 2014', size=(900, 400))
    m.bgcolor('#eee')  # more desktop-like
    print(m.proxy._runtime)
    app.run()
```

it should run in the webkit browser that comes with Qt. That bit is PyQt4/PySide only now. Maybe you want to make a PR to make it work with PyQt5 as well?

**Comment by stonebig** [comment]
argh, it tells me that (on Windows PyQt5.5.0):
````
Serving apps at http://localhost:54307/
ERROR:root:runtime process stopped (1), stdout:
Cannot import Qt<flexx.webruntime.qtwebkit.PyQtRuntime object at 0x0000000007594978>
````

**Comment by almarklein** [comment]
No, that's what I mean; Flexx does not support PyQt5 yet: https://github.com/zoofIO/flexx/blob/master/flexx/webruntime/qtwebkit.py
