### ISSUE TITLE
A fallback GUI to communicate with the user

### ISSUE THREAD

**Issue by almarklein** [zoofIO/flexx#261]
It would be nice to be able to communicate with the user via some sort of GUI. When Flexx is used from Python its often enough to print an error to the terminal, but in deployed apps this is not friendly and sometimes there simply is no terminal.

Possibilities:

* Something based on OpenGL. The current `flexx.lui` is a start in that direction, but should probably be removed. You'd need a lib to create the window for you, e.g. glfw, which is very small, but you'd need one for each platform that you want to support.
* Using ctypes and native calls: https://github.com/zoofIO/flexx/issues/222#issuecomment-249500840 though this would require a different implementation for Windows/OSX/Linux. Is it even possible to do on each platform?
* Using a simple web page (no JS). We're running Tornado already anyway (though what if we want to tell the user that Tornado is missing?). At least this approach should just work *anywhere* and should be relatively easy to maintain.

Native solutions:
* Windows: via ctypes using `windll.user32.MessageBoxW` but looks ugly for some reason.
* Windows: via `mshta `: `mshta "javascript:var sh=new ActiveXObject( 'WScript.Shell' ); sh.Popup( 'Message!', 10, 'Title!', 64 );close()"`
* Linux: Zenity seems pretty widely available https://en.wikipedia.org/wiki/Zenity (confirmed to even work on Raspberian)
* OSX: `osascript -e 'tell app "SystemUIServer" to display dialog "bla bla"'`

**Comment by almarklein** [comment]
cc @niki-sp

**Comment by Korijn** [comment]
https://github.com/cztomczak/cefpython ?

**Comment by ivoflipse** [comment]
Similarly like Django had /admin you could make a URL handler for showing logs and whatnot. Webapp2 has something similar.

**Comment by almarklein** [comment]
https://en.wikipedia.org/wiki/Zenity seems to be available on most Linux machines.

**Comment by almarklein** [comment]
OSX: `osascript -e 'tell app "SystemUIServer" to display dialog "bla bla"'`
