### ISSUE TITLE
Desktop-like web runtime based on Chromium

### ISSUE THREAD

**Issue by almarklein** [zoofIO/flexx#262]
XUL is great, but it would be nice to have something based on the Chromium engine too, because Firefox and Chrome excel in different areas (ok, I admit, Chrome is often faster).

Preferably just using Chrome/Chromium with a special flag, similar to how we run XUL.

**Comment by Korijn** [comment]
https://github.com/cztomczak/cefpython

**Comment by almarklein** [comment]
We now have a 'chrome-app' runtime that works well on Windows, but not so much on other OS's, and a 'nw-app' runtime based on NW.js (which uses the Chromium engine).
