### ISSUE TITLE
Modularize CSS

### ISSUE THREAD

**Issue by almarklein** [zoofIO/flexx#263]
Flexx might not be alone on the page. While the JS is (soon) pretty modular, CSS is sort of global by nature. We don't want our CSS to mess up other parts of the page, or silly mistakes in other people's CSS to mess up our widgets.

* All our class names should be prefixed with `flx-`. Even if we would use strict selectors like `.flx-Widget > hidden`, our `hidden` class can easily cause trouble elsewhere.
* For clarity, modifier class names should be `flx-mod-x`.
* All third party class names (in particular Phosphor) should be "under a `flx-Widget`", e.g. `.flx-Widget p-TabBar`.

Further notes regarding Phosphor: the `phosphor-all.css` should consist of Phosphor's standard CSS plus any CSS that we need to add to make things work, and (as outlines above) should be "prefixed" with `.flx-Widget p-XX`. That way our CSS should not harm the rest of the page, and can also be disabled as a whole.

**Comment by almarklein** [comment]
Other tips to write modular CSS are welcome.

**Comment by Korijn** [comment]
Some people use compiled CSS like SASS. Others apply naming schemes strictly. It's hard. :)

If all your elements are always inside a specific container, you could prefix literally all your selectors with `.flx-root` to avoid clashes.

**Comment by almarklein** [comment]
Implemented in #254
