### ISSUE TITLE
Can PyScript turn list comprehensions in map()?

### ISSUE THREAD

**Issue by almarklein** [zoofIO/flexx#267]
The generated code for a list comprehension is big and hard to read. I wonder if we can make it smarter and generate code that uses `map()` and `reduce()`.

**Comment by ivoflipse** [comment]
Though rewriting list comprehensions to lambda's that have complex if/else statements isn't much fun either

**Comment by Korijn** [comment]
Doesn't need to be a lambda; functions work too

**Comment by ivoflipse** [comment]
Yeah, but then each list comprehension will need a small custom function, which can get tedious too

**Comment by Maxyme** [comment]
@ivoflipse, list comprehension will be map function in JS. Nothing will change in python, you can use list comprehensions the same as before.

**Comment by almarklein** [comment]
While I'm in here ... does it make sense to prevent unselecting an item in certain cases? Right now an item can be unselected by clicking on it.

**Comment by almarklein** [comment]
I think that my feeling is that the tree view should not try to be a radiobutton-thing and that code that wants to behave it like that can probably make it so quite easily (if the last event is an unselect event, select it again).

**Comment by ivoflipse** [comment]
A radio-button generally only allows you to select one thing, wheres a tree (at least in Explorer/Qt/Wx) allows you to select multiple items at the same time. But to trigger the selected_index event, you generally have to double click, which you can only do on one item

**Comment by almarklein** [comment]
@ivoflipse the Flexx TreeWidget has a `max_selected` property by which one can specify how many items can be selected. Clicking on an item that is already selected will unselect it, which makes the most sense, I think.

**Comment by Maxyme** [comment]
@almarklein my opinion is that if the tree item is disabled, selection or deselection should not work, and the item should be grayed out.

**Comment by almarklein** [comment]
@Maxyme what do you mean by disabled?
