### ISSUE TITLE
video widget local file

### ISSUE THREAD

**Issue by JohnLunzer** [zoofIO/flexx#297]
Is there a way to get the video widget to play mp4 files located locally? I've tried every format for the url I could think of but the video isn't playing. I'm not too familiar with browser tech so I'm probably trying to break some rule.

Ultimately I'd like to be able to dump mp4 files into a folder locally and present a list of files in that folder to the user and when the user clicked on a video it would play in a video widget. Any help on getting me moving would be greatly appreciated.

**Comment by almarklein** [comment]
Apparently, browsers won't let you play local files directly, unless they were defined by the user using a file selector: http://stackoverflow.com/questions/8885701/play-local-hard-drive-video-file-with-html5-video-tag

You can make Flexx serve the video file though:
```py
from flexx import app, ui
url = app.assets.add_shared_data('myvideo.mp4', 'file://' + fname)
ui.VideoWidget(source=url)
```

A full example:
```py
import os
from flexx import app, ui

fname = 'd:/videos/ice age 4 trailer.mp4' 
assert os.path.isfile(fname)
url =app.assets.add_shared_data('myvideo.mp4', 'file://' + fname)
app.App(ui.VideoWidget, source=url).launch()
app.run()
```

The downside of this approach is that Flexx loads the complete video file in memory, which is ok from small videos, but don't try that with the full Lord of the Rings trilogy ;)

I can see this as a perfectly fine use-case though, so maybe Flexx should support serving files via the filesystem; as a proxy rather than reading it into memory.

**Comment by Korijn** [comment]
Any "static file server" can provide you with URLs though. Try `nginx`!

**Comment by almarklein** [comment]
True, and Tornado too, but would be nice if Flexx can make this a no-brainer.

**Comment by JohnLunzer** [comment]
Thank you for your responses, you mentioned that Tornado can do it, can [this Flexx example of adding handlers](https://github.com/zoofIO/flexx/blob/a3ab59005ae4ff5513b3d73d22cca4fd6a8b3629/flexx/app/examples/adding_handlers.py) be modified and added too the example above to include the static local content without fully loading it into the browser first?

I ask because tornado has a [tornado.web.StaticFileHandler](http://www.tornadoweb.org/en/stable/web.html) class, but I can't figure out exactly how it would fit into Flexx.

**Comment by almarklein** [comment]
Oh nice, that turns out to be pretty easy!

```py

import os
from flexx import app, ui

tornado_app = app.current_server().app
from tornado.web import StaticFileHandler

tornado_app.add_handlers(r".*", [
    (r"/videos/(.*)", StaticFileHandler, {"path": "d:/videos"}),
    ])

url = '/videos/ice age 4 trailer.mp4'
app.App(ui.VideoWidget, source=url).launch()
app.run()
```

**Comment by almarklein** [comment]
Maybe we could add `app.assets.add_data_dir(local_dir, url_path)` to streamline the above.

**Comment by JohnLunzer** [comment]
Beautiful! Now the video shows up immediately, streaming in the normal fashion.

**Comment by JohnLunzer** [comment]
Additionally the streamlined pattern you provided would be welcome, I think it adds enormous value to Flexx. 

Just a note, this is from the Tornado docs:
```
StaticFileHandler is intended primarily for use in development and light-duty file serving; for heavy traffic it will be more efficient to use a dedicated static file server (such as nginx or Apache). 
```
It might be worth adding that to the docs or the docstring for figure add_data_dir method.

**Comment by almarklein** [comment]
Getting this in #313, including a small example to list and view videos from your local machine and the web.

**Comment by almarklein** [comment]
So eventually I decided against having a static file handler in Flexx by default for secutity reasons. There is a niew `video_viewer.py` example which demonstrates how to setup a static file server with tornado.
