### ISSUE TITLE
Q: Mouse events on dynamically generated components?

### ISSUE THREAD

**Issue by alexveden** [zoofIO/flexx#298]
Is that possible to handle events fired by dynamically generated components?

I'm using flex 0.4.1, installed by pip

Very excited about flexx project, it will make IPy notebooks shine. Thx.

For example, simple file viewer app:

`
class FileViewer(ui.Widget):           
    
    def init(self):
        with ui.HBox():
            with ui.VBox(flex=1):
                with ui.VBox():
                    with ui.GroupWidget(title='Available files') as self.file_list:

                        # Generating files list
                        for file in os.listdir('/'):
                            ui.Label(text='{0}'.format(file))                    
                            
                ui.Widget(flex=1)

            with ui.VBox(flex=3):
                with ui.GroupWidget(flex=3, title='Source code view'):
                    self.file_contents = ui.Label(wrap=True, text='' )
    
    @event.connect('mouse_down')
    def _print_file_contents(self, *events):
       # TODO:        
        # Get clicked label or text or object instance. How can I implement that?
        
        # Get file name        
        # Read the file contents        
        # Display them in self.file_contents text area        
        `

**Comment by almarklein** [comment]
You can do `@event.connect('file_list.children*.mouse_down')`. I *think* this was already in 0.4.1, if not, please try master.

**Comment by almarklein** [comment]
Oh, that should be `'file_list.children.*.mouse_down'` in 0.4.1 (note the dot), current master allows both versions.

**Comment by alexveden** [comment]
Great, thx, it works!
