### ISSUE TITLE
Add autoplay option to VideoWidget

### ISSUE THREAD

**Issue by JohnLunzer** [zoofIO/flexx#302]
I created a small demonstration which lists files from a directory in a treeWidget and when an item is double clicked the source is changed in a VideoWidget. It's doing pretty much what I want it to but I'd like to have the videos autoplay when they load up. I tried to modify the source myself but I don't understand the JS well enough.

Here is my demo:
```python
import os
from flexx import app, ui, event
from tornado.web import StaticFileHandler

basePath = "/media/video"

class VideoViewer(ui.Widget):
    def init(self):
        with ui.SplitPanel(orientation='h'):
            with ui.TreeWidget(title='Available files', flex=1, max_selected=1) as self.tree:
                for file in os.listdir(basePath):
                    ui.TreeItem(text=u'{0}'.format(file))
            self.vid1 = ui.VideoWidget()

    class JS:
        @event.connect('tree.items**.mouse_double_click')
        def on_event(self, *events):
            for ev in events:
                url = "/video/" + ev.source.text
                self.vid1.source = url

tornado_app = app.current_server().app
tornado_app.add_handlers(r".*", [
    (r"/video/(.*)", StaticFileHandler, {"path": basePath}),
    ]) 

app.App(VideoViewer).launch()
app.run()
```

**Comment by almarklein** [comment]
You'd need to set the `autoplay` attribute of the `<video>` element. I think adding this to the `JS` nested class should work:
```py
    init(self):
        self.vid1.node.autoplay = 'autoplay'
```

**Comment by JohnLunzer** [comment]
Thanks, I'll try that, I'm sure it will work. I'm still getting to grips with Flexx.

**SLIGHTLY TANGENTIAL MUSING FOLLOWS**

I understand that Flexx is in part an attempt to bridge Python and Javascript. I understand also that the GUI elements of Flexx originate from the phosphor JS package. If I could draw an analogy. The PyQt package makes little if any demands on the user to understand C++ (the native language of Qt). 

Do you have any goals of providing that same level of abstraction to Flexx in the future? I realize the implications of that could affect the "bridge" aspect of Flexx. With careful design I believe the UI component of Flexx could have an API which made no demands on the user to have knowledge of JS/HTML/CSS. I'm not saying that having knowledge of those languages is a bad thing, but along with the "bridge" component Flexx touts "Apps are written purely in Python". Based on my short experience with Flexx I feel like while that is technically true, a more honest statement would be "Apps are written purely in Python, with some knowledge of Javascript, HTML, and CSS." 

Anyway, I don't think that it's really an issue or something that needs your attention in the short term, but maybe something to think about in the long term.

**Comment by JohnLunzer** [comment]
Just tested, worked perfectly, thank you.

**Comment by almarklein** [comment]
Thanks for bringing up the issue about the usability of `flexx.ui` for non web devs. I think its important enough to have a discussion in a separate issue (#305).
