### ISSUE TITLE
Missing requirement: tornado?

### ISSUE THREAD

**Issue by e12e** [zoofIO/flexx#31]
Hi,

I tried testing the example from the readme in a (fresh) virtualenv:

```shell
pyvenv flex.test
./flex.test/bin/pip install ./flexx.git # Same result if pulling from pypy with "pip install flexx"
cat <<eof > ex.py
#code from readme omitted
eof
./flex.test/bin/python ./ex.py
Traceback (most recent call last):
  File "ex.py", line 1, in <module>
    from flexx import app, ui, react
  File ".../flex.test/lib/python3.4/site-packages/flexx/app/__init__.py", line 61, in <module>
    from .proxy import run, start, stop, init_notebook, call_later
  File ".../flex.test/lib/python3.4/site-packages/flexx/app/proxy.py", line 10, in <module>
    import tornado.ioloop
ImportError: No module named 'tornado'
```

Added tornado to `install_requires` (I use mercurial hg-git):

```diff
$ hg diff -c -1
diff -r d14c42b51483 -r 55b0b4821a5c setup.py
--- a/setup.py  Sat Sep 05 13:57:35 2015 +0200
+++ b/setup.py  Sun Sep 06 13:33:49 2015 +0200
@@ -63,7 +63,7 @@
     long_description=__doc__,
     platforms='any',
     provides=[name],
-    install_requires=[],
+    install_requires=['tornado'],
     packages=package_tree(name),
     package_dir={name: name},
     package_data={},
```

Then virtualenv/pip sets things up correctly, and everything works. Does seem to be awfully few install_requires... Is this a TODO-item?

**Comment by almarklein** [comment]
Some submodules in Flexx (PyScrip, React, WebRuntime) do not have any dependencies. The app and ui submodules do require tornado. Since these former submodules can be used on their own, I am reluctant to add tornado to setup.py. Instead I'd put a note in the installation section of the docs.

In time these submodules should perhaps be factored out in their own packages, but for now I prefer to keep them together.

**Comment by mgaitan** [comment]
@almarklein you should declare them as setuptool's "extra requires" 

https://pythonhosted.org/setuptools/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies

so, suppose you declare extra_require for "app" as 

        extras_require = {'app': ['tornado', ...]}

then you can force install those extra dependencies with pip 

       $ pip install flexx[app]

you could also add an `'all`' key listing every dep.  Check the setup of one of my projects as an example:

https://github.com/mgaitan/waliki/blob/master/setup.py#L28-L41

**Comment by almarklein** [comment]
@mgaitan Thanks, that seems like a good approach! @e12e you want to do this? Otherwise I'll probably do it sometime this week.
