### ISSUE TITLE
Improve SplitPanel to respect flex values and allow spacing

### ISSUE THREAD

**Issue by JohnLunzer** [zoofIO/flexx#310]
*Original title: Can flex spacing be used with SplitPanel?*

If not, is there a way to set the spacing/ratio of split panels? Adding the `flex` parameter to widgets within a SplitPanel context does not have the desired effect.

**Comment by almarklein** [comment]
Phosphor does support it, but Flexx does not wrap it yet: http://phosphorjs.github.io/phosphor-splitpanel/api/classes/splitpanel.html#spacing

Similarly, I agree that setting `flex` should be usable to set the relative sizes.

**Comment by almarklein** [comment]
So the spacing can for now be set in JS using `self.phosphor.spacing = 10`.

**Comment by JohnLunzer** [comment]
Hehe, self.phosphor.spacing = 10 causes the split bar in the middle to be 10 pixels wide.

Looks like I would have to use the setSizes function: http://phosphorjs.github.io/phosphor-splitpanel/api/classes/splitpanel.html#setsizes

I can't quite figure out how to directly call a JS class method

**Comment by Korijn** [comment]
`self.call_js('foo(1, 2)')` will be called on `self` on the JS side

**Comment by JohnLunzer** [comment]
@Korijn, my attempts to apply that to the phosphor element and the setSizes class method have all run into JS errors.

**Comment by Korijn** [comment]
`self.call_js('phosphor.setSizes(100, 100)')` does that work for you?

**Comment by JohnLunzer** [comment]
No, I'm getting an error. I'm sure I'm doing this wrong:
```python
class SpaceSplitPanel(ui.SplitPanel):
    def init(self):
        self.call_js('phosphor.setSizes(100, 100)')
    class JS:
        def init(self):
            self.phosphor.spacing = 0
```
My error is:
```
JS - TypeError: flexx.instances.SpaceSplitPanel2.phosphor.setSizes is not a function (stack trace in browser console)
```

**Comment by almarklein** [comment]
It looks like `setSizes()` is old. Use this instead: https://github.com/phosphorjs/phosphor/blob/master/src/ui/splitpanel.ts#L581-L591

You can call `self.phosphore.setRelativeSizes(...)` from the JS's init where you set the spacing too. The `call_js` method is intended for when you need to invoke a JS function from Py.

**Comment by JohnLunzer** [comment]
You're right. This works... but, it has no effect from the JS's init function. It will work if called after init. See my example below:

```python
class SpaceSplitPanel(ui.SplitPanel):
    @event.emitter
    def updateSplitPanel(self):
        return dict()

    class JS:
        def init(self):
            self.phosphor.setRelativeSizes([1,3])
            self.phosphor.spacing = 0
        
        @event.connect("updateSplitPanel")
        def update(self, *events):
            self.phosphor.setRelativeSizes([1,3])
```

I added the emitter so that I could trigger the update after I had set my split widgets. Without the emitter and calling ```updateSplitPanel()``` the call to ```setRelativeSizes``` in the JS init() has no effect.

Please let me know if you can replicate. If not I will provide my full example rather than just the subclassed widget.

**Comment by Korijn** [comment]
Maybe you have to call `super().init()`?

**Comment by almarklein** [comment]
I can reproduce it (also with calling `super().init()`). I suspect the Phosphor widget is not fully initialized at that point (maybe it needs a reflow first?).

**Comment by JohnLunzer** [comment]
@almarklein out of curiosity, is the way that I worked around it the easiest way? Like I said I'm still coming to grips with Flexx and I didn't see any kind of "post-init processing" JS method which might have been appropriate for this.

**Comment by Korijn** [comment]
You would expect that Phosphor doesn't return until the widget is ready to go, but apparently that's not the case. I think that's the underlying assumption that Flexx made here.

**Comment by JohnLunzer** [comment]
There _may_ be another reason. The setRelativeSizes method of the SpiltPanel Phosphor widget takes a `number[]` array as an argument. If it has less numbers than the amount of splits it fails and if it has more it ignores the "extras". During init() my guess is that the split has only one panel. When the array passed through setRelativeSizes it operates on the the private member vector "_sizers" but doesn't look to store the passed array. 

I tested moving my custom updateSplitPanel() method prior to added any widgets:
```python
def init(self):
    with SpaceSplitPanel(orientation='h') as self.split:
        self.split.updateSplitPanel()
        # Add widgets
```
and _it actually sets the splits appropriately_... so that test doesn't support my theory.

Either way, from the behavior it seems setRelativeSizes should still work perfectly with the `flex` argument. And if somebody wanted to do it from init() you could still have some sort of instance member which stored the array for setRelativeSizes and checked on that each time a new widget was added to the SplitPanel in case a `flex` argument wasn't passed with the constructor.

**Comment by almarklein** [comment]
Try this:
```py
class SpaceSplitPanel(ui.SplitPanel):
    def init(self):
        ui.Widget(style='background:#a00', flex=1)
        ui.Widget(style='background:#0a0', flex=2)
        ui.Widget(style='background:#00a', flex=4)
    
    @event.emitter
    def updateSplitPanel(self):
        return dict()

    class JS:
        def init(self):
            self.phosphor.spacing = 15
            window.setTimeout(0.01, self._set_flexes)  # Phosphor seems to need one iter to "settle"
        
        @event.connect("updateSplitPanel")
        def update(self, *events):
            self.phosphor.setRelativeSizes([1,3])
            
        @event.connect('children', 'children*.flex')
        def _set_flexes(self, *events):
            i = {'h': 0, 'v': 1}[self.orientation]
            flexes = [w.flex[i] + 0.1 for w in self.children]
            self.phosphor.setRelativeSizes(flexes)
```

**Comment by almarklein** [comment]
BTW: if you're using a spacing of 0, you cannot grab the splitter anymore, in which case you might as well use a BoxPanel.

**Comment by JohnLunzer** [comment]
Ahh, beautiful fix, this works and is what I will use until this is rolled into the master. I'm constantly impressed by Flexx's architecture.

In my example when I'm using a TreeWidget on the left split and a VideoWidget on the right split I find that setting the spacing to 0 still allows me to grab the splitter.

**Comment by JohnLunzer** [comment]
Thanks, when I get a few free minutes I will test it out
