### ISSUE TITLE
Prevent default action for Ctrl+F 

### ISSUE THREAD

**Issue by JohnLunzer** [zoofIO/flexx#312]
I tried to follow the example in here: https://github.com/zoofIO/flexx/blob/master/flexx/ui/_widget.py.

But it's not clear to me where (top level widget?) to add the overloaded key_press method and it's also not clear how to take into account modifier keys.

Any help would be appreciated.

**Comment by Korijn** [comment]
Here's how you can override the event emitter so you can work with the actual browser event object. Note the difference between `e` (browser event) and `ev` (Flexx-wrapped event).

```python
def Foo(ui.Widget):
    @event.emitter
    def key_press(self, e):
        ev = super().key_press(e)
        if ev.key == 'F' and ev.modifiers == ['Ctrl']:
            e.preventDefault()
        return ev
```

**Comment by JohnLunzer** [comment]
Thanks, that got me started. Please see this [SO post, with reference links,](http://stackoverflow.com/a/11181954/3991139) stating that Chrome recognizes `key_down` rather than `key_press`. Thusly, overriding `key_down` should probably be used for cross-browser compatibility (Chrome/FF). 

I tested the `key_down` override and it works in both browsers. The `key_press` override only works in Firefox.

**Comment by Korijn** [comment]
Huh! I hadn't encountered that yet myself. Perhaps you should override both then.

**Comment by JohnLunzer** [comment]
@almarklein, perhaps with my comment above, if you feel it appropriate, the example at https://github.com/zoofIO/flexx/blob/master/flexx/ui/_widget.py#L699 should be modified.
