### ISSUE TITLE
Detecting closed session in the ui.Widget instance

### ISSUE THREAD

**Issue by eudoxos** [zoofIO/flexx#319]
I am running separate thread to continuously update UI and I would like to detect the session ending somehow. Otherwise the console is overflowing with "Cannot send commands; app is closed" for old sessions. I have something like this:
```
class MyApp(ui.Widget):
   def init(self):
       import threading
       threading.Threads(target=self.updates_thread).start()
   def updates_threads(self):
      white True: ## ???
         self.emit('event_baz',dict(foo=bar))
   class JS:
       @event.connect('event_baz')
       def _handle_event_baz:
          # update UI

```

I would like to replace `while True` with something like `while self.session.open()` so that the thread exits with the session. Is there API for this?

**Comment by almarklein** [comment]
You can use `model.session.status` to [detect](http://flexx.readthedocs.io/en/latest/app/api.html#flexx.app.Session.status) whether the session is still alive. See e.g. the chatroom example.
So I guess that would be `while session.status:` in your example.

Another approach could be to implement the `dispose()` method of the root widget (or any widget really, for which you know that it wont be deleted before the session closes):
```py
class MyMainWidget(ui.Widget):
    def dispose(self):
         super().dispose()
         # ... do clean up or notify other parts of the app
```
