### ISSUE TITLE
Trivial typo in classic_web_dev_src.html

### ISSUE THREAD

**Issue by zunzun** [zoofIO/flexx#327]
The file classic_web_dev_src.html online reads,

"or embed plain of HTML inside one such widget"

I think that should be "plain *old* HTML" and not "plain *of* HTML"

**Comment by almarklein** [comment]
Thanks! I snuck a fix in the PR that I am not working on. For next time, you can also consider [searching](https://github.com/zoofIO/flexx/search?utf8=%E2%9C%93&q=plain+of+HTML) for the code, and fixing it via the Github interface. That way you get the credits :)
