### ISSUE TITLE
Support legacy Python (py 2.7)?

### ISSUE THREAD

**Issue by almarklein** [zoofIO/flexx#33]
Via six.py or python-future.org

I'm a bit tired of making stuff work on both Python2 and Python 3. I just want to write `isinstance(c, str)`. But maybe to get Flexx out there and usable from existing projects, I'd have to give in. We'll see.

PyScript support is the trickiest bit, I suppose, because the ast parser behaves slightly different. But the ast parse of pypy is different too, and I very much like to support that. Having a pure Python ast parser would be even more awesome, see #19.

**Comment by stonebig** [comment]
Taking care of Legacy Python may only slow you down and limit yourself, with no short-term nor long term benefit.

**Comment by almarklein** [comment]
Well ... if an existing project wants to make use of Flexx, but would need it to be 2.7 compatible ... this might (under some circumstances) be a "political" argument in favour to support legacy Python.

**Comment by stonebig** [comment]
will there be a 0.2 soon ? (now the euroscipy video is out)

**Comment by almarklein** [comment]
Sure, we could do a release soon.

**Comment by show0k** [comment]
Lot of scientific tools use python 2.7 (the last example is the Google deep network library TensorFlow which is not python 3 compatible) because it's faster...
 It is a mess to support python 2.7 from python 3.4+ but I think it would be useful for many people !

**Comment by datnamer** [comment]
Actually, I think 3.5 is faster now....and we have the matrix multiply operator.

**Comment by almarklein** [comment]
It's likely that at least the PyScript subpackage will become 2.7 compatible. Depending how easy it is to keep developing as a 3.x package and "translating" to 2.7 during install-time, we might just make everything compatible.
