### ISSUE TITLE
Example benchmark.py fails on python 2.7

### ISSUE THREAD

**Issue by rddaz2013** [zoofIO/flexx#330]
I get errors...

Pystone(1.1) time for 50000 passes = 0.668819
This machine benchmarks at 74758.6 pystones/second

  File ".../flexx/test_my/bench.py", line 184, in <module>
    b.benchmark()
  File ".../flexx/test_my/bench.py", line 166, in benchmark
    convolve()
  File ".../flexx/test_my/bench.py", line 69, in convolve
    data = window.Float32Array(N)
TypeError: unbound method Float32Array() must be called with window instance as first argument (got int instance instead)

Python 2.7.12 |Anaconda 2.3.0 (64-bit)| (default, Jul  2 2016, 17:42:40) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2

**Comment by almarklein** [comment]
Reproduced for Python 2.7
