### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Telmtone** [zoofIO/flexx#34]
Hi,

Looks like a great library and trying to feel out the python space for doing this stuff.  I'm pretty new to python (and programming) and brand new to web programming so please excuse  the following the noob questions as I had already persued the docs. 

1. Is it possible to call arbitrary JS packages like vega from pyscript both in flexx or from python programs? 

2. Can I use flexx as a django frontend? 

3. Can I call use UI components from other libraries like Polymer and Angular? 

Thanks!

**Comment by almarklein** [comment]
> 1. Is it possible to call arbitrary JS packages like vega from pyscript both in flexx or from python programs? 

Yes, you can call anything you want. If you write `foo.bar()` in PyScript, it translates to exactly that in JS. However, you need a way to load the external JS library somehow. I think Flexx should probably support that at some point, but it doesn't now.

> 2. Can I use flexx as a django frontend? 

Not sure. I'm not familiar enough with django to tell. No idea what that would look like. Also not sure if it makes sense to do it.

> 3. Can I call use UI components from other libraries like Polymer and Angular? 

Partly the same answer as for (1). Polymer is more of a declarative HTML(ish) language. You wont be able to write that, but maybe its possible to instantiate components by creating the appropriate DOM elements.

**Comment by Telmtone** [comment]
Got it. 

> However, you need a way to load the external JS library somehow. I think Flexx should probably >support that at some point, but it doesn't now.

Yes that would be really cool and useful for me and I'm guessing alot of people that Just want to  get stuff done  in python! I would offer to help, but I assume it requires knowing javascript. 

> maybe its possible to instantiate components by creating the appropriate DOM element

I plan to play around with this.

**Comment by almarklein** [comment]
Flexx now has a way to specify and then use additional assets. See e.g. the source for the Bokeh Widget or this example: https://github.com/zoofIO/flexx/blob/master/examples/ui/with_jquery.py
