### ISSUE TITLE
Request: Document the process of writing a widget from scratch.

### ISSUE THREAD

**Issue by drafter250** [zoofIO/flexx#342]
The Documentation for flexx is really great so far!
but I am having some trouble understanding how I would access attributes of any HTML elements comprising a widget and or customize the behavior of an existing widget when subclassing it.

Overall I keep feeling like I am running up against not understanding how a widget is actually written.

I was trying to see how I could possibly transform the LineEdit Widget into a `<input type='file'></widget>`.

it seems like this is the portion of the LineEdit Widget I need to look at:

``` python
    class JS:
    
        def _init_phosphor_and_node(self):
            
            # self.phosphor = window.phosphor.createWidget('input')
            # self.node = self.phosphor.node
            # self.node.type = 'text'  
            # self.node.list = self.id  -> readonly!
            
            # Some hacking to create an element with custom HTML
            # todo: Maybe we can make createWidget accept HTML instead
            ori = window.phosphor.widget.Widget.createNode
            def _():
                d = window.document.createElement('div')
                d.innerHTML = '<input type="text", list="%s" />' % self.id
                return d.childNodes[0]
```
Maybe I am missing something but it seems like all the pieces are documented fairly well like the pyscript module and the models and the widgets themselves but the actual process of taking some HTML, and one of the phosphor widgets and turning it into something usable I feel would go a long way. And maybe make it easier for others to contribute?

 If I can figure out how to do a File Input Widget I would love to be able to submit a PR for one :)

**Comment by almarklein** [comment]
I totally agree this needs better docs. But this is covered by #305, so closing this :)
