### ISSUE TITLE
Button Event counting

### ISSUE THREAD

**Issue by ziadanex99** [zoofIO/flexx#357]
Hi, im new to python and i stumbled on Flexx the other day.
since then i was IN to Flexx.

i create a simple counting script and its not working. When im creating a counter, i set my variable count as a global, this approach usually works for me.

but here its not working, when i click the button its not showing the couter value.

``` py
from flexx import app, ui
from flexx import event

@app.serve

class Form(ui.Widget):  

    def init(self):
        self.addBtn = ui.Button(text='ADD')
        self.outputLabel = ui.Label(text = 'Counter')

    class JS:
        count = 0
        @event.connect('addBtn.mouse_click')
        def _click_addBtn(self, *events):
            global count
            self.outputLabel.text = count
            count += 1

example = app.launch(Form)
app.export(Form, 'example.html')
```

thanks

**Comment by almarklein** [comment]
Hi, `count` is not a global, but an attribute of the `Form` class (at the JS side). The best way to do what you want is:

```py
    class JS:
        
        def init(self):
            self.count = 0
        
        @event.connect('addBtn.mouse_click')
        def _click_addBtn(self, *events):
            self.outputLabel.text = self.count
            self.count += 1
```

In general, its best to avoid globals for dynamic variables.

**Comment by ziadanex99** [comment]
Hi, Thanks. counter is working.

So basically if i need a dynamic variable I need to declare it locally within the JS class.

But how about import module such as time and datetime?

`from flexx import app, ui
from flexx import event
import time
import datetime

@app.serve

class Form(ui.Widget):  
    .............
    class JS:
        def init(self):
            # self.count = 0
            t = time.time()
            self.dt = datetime.datetime.fromtimestamp(ts).strftime('%Y-%m-%d %H:%M:%S')

        @event.connect('addBtn.mouse_click')
        def _click_addBtn(self, *events):
            self.outputLabel.text = self.dt
            count += 1

example = app.launch(Form)
app.export(Form, 'example.html')`

i got an error flag from chrome console says "Uncaught ReferenceError: time is not defined"
does this mean function time cant be converted in this approach?

Thanks,

**Comment by almarklein** [comment]
> So basically if i need a dynamic variable I need to declare it locally within the JS class.

Yes. If its a variable used internally only in JS, its generally best to do as I showed in my previous post. If you want to expose the variable, make it a property. And if that property should also be available in Python, make it a property on the `Both` class.

> But how about import module such as time and datetime?

Flexx can use any function/class in JS as long as it (and its dependencies) are PyScript compatible. This is the case for just a few Python modules. Time and datetime are not among them. There is a tiny bit (not-well-yet documented) support for the `time()`  and `perfcounter()` functions. But for anything else you'll need to use the JavaScript stuff (e.g. `Date()`).

**Comment by almarklein** [comment]
BTW, a small tip on the markdown format to include code in your posts: use tripple backquotes for multi-line code. As below, but without the spaces:
```
` ` ` py
code
` ` `
```

**Comment by ziadanex99** [comment]
Hi! Thanks for the feedback and for the small tips really appreciated.
Ill check all the thing mentioned, specially the PyScript compatibility with JS.

Flexx is very interesting, Im looking forward to it.

Thanks.
