### ISSUE TITLE
PyPy3.5 test results!

### ISSUE THREAD

**Issue by TiberiumPY** [zoofIO/flexx#366]
I've run flexx test suide with latest PyPy3.5 nightly (there's no official release yet - it's a PyPy with Python 3.5 support)
Results are there - https://paste.pound-python.org/show/JnqHZvJrRj1WPMPF5CgH/

Just wanted to inform you :)
Flexx is a great project :+1:

**Comment by almarklein** [comment]
Thanks! And the fail seems more like a "broken" test rather than something related to pypy.

FYI we do test on Pypy3 (Python 3.2.5 on Travis) and CPython 3.5. Still, it's good to know for sure things work there :)

**Comment by TiberiumPY** [comment]
PyPy3 is very old release (from 2014)

**Comment by almarklein** [comment]
Mmm, can I make Travis use a newer version? [This page](https://docs.travis-ci.com/user/languages/python/#PyPy-Support) seems to suggest that `"pypy-5.3.1"` can also be used.
