### ISSUE TITLE
License texts of included projects (e.g. Phosphor) should be in the source

### ISSUE THREAD

**Issue by almarklein** [zoofIO/flexx#40]
To avoid this: https://github.com/twosigma/beaker-notebook/issues/2651
Handled in Bokeh with this: https://github.com/bokeh/bokeh/issues/2958

**Comment by stonebig** [comment]
hi Almar,

small questions trying the `with_bokeh.py` example:

````
Bokeh: WebGL is not supported, falling back to 2D canvas
````
Do I need the dev version of Bokeh ?

````
Downloading http://raw.githubusercontent.com/zoofIO/phosphor-all/07578ac/phosphor-all.js
````
That is interesting, what part of the code does this ? (I don't find it , and would like to pre-download it eventually)

**Comment by almarklein** [comment]
No, this means your browser does not support webgl. With 1000 points that plot also dont really needs webgl. You can remove the `webgl=True` in the figure functions to just use canvas.
