### ISSUE TITLE
RxPy

### ISSUE THREAD

**Issue by datnamer** [zoofIO/flexx#49]
https://github.com/ReactiveX/RxPY 

Have you seen this? Maybe better to use that than maintain your own FRP framework.

**Comment by stonebig** [comment]
the guy is from Microsoft, but not the tool itself http://pythonpodcast.com/dag-brattli-rxpy.html , so you may not say "Microsoft"

**Comment by datnamer** [comment]
Ok fixed

**Comment by almarklein** [comment]
Thanks for the link. Will have a look soon.

**Comment by datnamer** [comment]
Sure. Also bokeh might find it useful as well for the new server. Would you mind tossing it into the right discussion if you think its worthwhile?

**Comment by almarklein** [comment]
I had a look, and also reconsidered `flexx.react`. Frankly, I am not enthousiastic about RxPy, as it all seems rather complicated, and if anything, we should simplify the system.

I am preparing for a new system #60 which is more like a classical event system, but with some of the current RP-inspired nicities mixed in.

**Comment by datnamer** [comment]
Gotcha. Makes sense.
