### ISSUE TITLE
Maybe worth a look - new Python to JavaScript compiler

### ISSUE THREAD

**Issue by pya** [zoofIO/flexx#89]
Advertised as:

- Small, highly readable JavaScript code
- Almost no runtime overhead w.r.t. JavaScript
- Implementation of a large part of Python 3.5 including multiple inheritance, properties, **args and *args, comprehensions, bound function pointers, hierarchical modules etc.
- Seamless and elegant integration with any JS library

http://www.transcrypt.org/

**Comment by almarklein** [comment]
Thanks @pya  Yes, I was recently made aware and already reached out (see their issue nr. 1). Transcript indeed has very similar goals, follows a very similar approach and has very similar (planned) features. From what I can tell, the features that it has/will have that pyscript has not are multiple inheritance, bound functions and **kwargs. I think having at least bound functions is probably a good idea...
